"""add podcast model

Revision ID: 084f1dbc3c8c
Revises: 9fe03ecf867f
Create Date: 2026-02-06 20:29:29.062442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084f1dbc3c8c'
down_revision: Union[str, Sequence[str], None] = '9fe03ecf867f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('character_alignment', sa.String(), nullable=True),
    sa.Column('word_alignment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_table('podcasts')
    # ### end Alembic commands ###
