"""add podcast transcript

Revision ID: 7d33da9a52df
Revises: 084f1dbc3c8c
Create Date: 2026-02-07 22:26:13.824563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d33da9a52df'
down_revision: Union[str, Sequence[str], None] = '084f1dbc3c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcasts', sa.Column('transcript', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcasts', 'transcript')
    # ### end Alembic commands ###
