"""resource emoji

Revision ID: 9fe03ecf867f
Revises: 8278d03bab8d
Create Date: 2026-01-29 17:47:32.411641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe03ecf867f'
down_revision: Union[str, Sequence[str], None] = '8278d03bab8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_resources', sa.Column('emoji', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_resources', 'emoji')
    # ### end Alembic commands ###
