"""more resource states

Revision ID: d63b2fd6c38d
Revises: 75c759c93f67
Create Date: 2025-09-10 16:43:35.248230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63b2fd6c38d'
down_revision: Union[str, Sequence[str], None] = '75c759c93f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_resources', 'resource_type',
               existing_type=postgresql.ENUM('PDF', 'YOUTUBE_LINK', 'AUDIO', 'TEXT', name='learningresourcefiletype'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('learning_resources', 'status',
               existing_type=postgresql.ENUM('PROCESSING', 'COMPLETED', 'FAILED', name='resourcestatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_resources', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PROCESSING', 'COMPLETED', 'FAILED', name='resourcestatus'),
               existing_nullable=True)
    op.alter_column('learning_resources', 'resource_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PDF', 'YOUTUBE_LINK', 'AUDIO', 'TEXT', name='learningresourcefiletype'),
               existing_nullable=True)
    # ### end Alembic commands ###
